apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: hfmlk8bii-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hfmlk8bii-go 
  name: hfmlk8bii-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: hfmlk8bii-go
    weight: 100 
