apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hfmlk8bii-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hfmlk8bii-go 
  name: hfmlk8bii-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hfmlk8bii-go 
